### PR TITLE
Tree

### PR DESCRIPTION
**Pull request by Ge0**
this PR aims at refactoring the codebase to move it into a *src* sub-package. There are several arguments to doing so:

  - First, when I am typing `discurses` on the project's directory, my shell actually makes me `cd` into `discurse`directory containing the source code.
  - It is more convenient to have the source code into a separate directory in order to avoid confusion with $PYTHONPATH.

Cf https://blog.ionelmc.ro/2014/05/25/python-packaging/ for more information.

Plus I have moved `discurses.py` into `discurses/__main__.py` and added an `__about__.py` file for metadata information.

### CODE REVIEW

**Comment by topisani** [comment]
looks good - however, 0.3.0 has been released, so  if you could update the __about__.py file to reflect that, great! i forgot about the changelog thats why there's no entry in it

**Comment by Ge0** [comment]
Done, my good sir!

Also, we were still displaying the former version number. This is fixed.

I don't know the actual summary in the changelog anyway.

**Comment by Ge0** [comment]
Plus I have edited the readme to ask for Python 3.6 since I use the new format string syntax.

**Comment by topisani** [comment]
nice!

**Pull request merged**
