### PR TITLE
Update message_list.py

### LINKED ISSUE #6: Scale columns acording to their contents
See screenshot:
screenshot_2016-10-06_13-58-05

Possible fix: truncate usernames to fixed max length.

### PR DESCRIPTION
**Pull request by shrx**
better column formatting

not thorougly tested.

fixes #6

### CODE REVIEW

**Comment by shrx** [comment]
screenshot:
screenshot_2016-10-06_15-44-03

**Comment by topisani** [comment]
are the columns adjusted to the width of their contents?

**Comment by topisani** [comment]
actually, it looks great, lets merge!

**Comment by topisani** [comment]
hmm i seem to be getting slightly different results...
img-2016-10-06-164302
Its been a long time since i looked at any of this code, what exactly is supposed to happen here? is it just the right alignment? cause I'd like to reduce the whitespace between the columns in that picture...

**Comment by shrx** [comment]
This looks right; the total width is fixed and is defined with these lines of code:
https://github.com/shrx/Discurses/blob/cac3bc4f2f052861dba775713611df990857bebb/discurses/ui/message_list.py#L234
https://github.com/shrx/Discurses/blob/cac3bc4f2f052861dba775713611df990857bebb/discurses/ui/message_list.py#L237

Can I add you on discord so we can chat? Join this server: https://discord.gg/tmYBv

**Comment by topisani** [comment]
Om away until sunday and probably wont have a Lot of time till then. Ill join your discord now though, i have a bit of time on this train🚄🚄

**Pull request merged**
