### PR TITLE
add authentication instructions

### PR DESCRIPTION
**Pull request by shrx**

### CODE REVIEW

**Comment by topisani** [comment]
Nice! i didnt know anyone was actually using this. Feel free to suggest features and report errors, but im not currently working a lot on it. PR's are much apreciated!

**Comment by shrx** [comment]
I have been trying to use several CLI discord clients, and right now your seems to be the best. Most, if not all others are not being actively developed so they're missing new functionalities, and/or have a very unintuitive interface.

**Comment by topisani** [comment]
the intuitive user interface was my biggest focus. For features i really recommend discorder. Discurses is still missing a few things, but id like to add them at some point. If you (or anyone else ever reading this) is up to it, there are a lot of small things, even documentation, that would be great to get some help on! anyways i apreciate this, its something i always meant to do.

sidenote:
discurses can be installed with `pip install discurses`, idk if it says that anywhere

**Comment by shrx** [comment]
It does at least in the commit logs, that's how I installed it and didn't have any issues.

**Comment by topisani** [comment]
oh yeah, it does. Anyway, i apreciate the help, and its always welcome!

**Pull request merged**
